/**
 * Admin portal mock data.
 *
 * All exported arrays are consumed by src/lib/admin/service.ts.
 * Replace each service function with a real Prisma query when backend is ready.
 */
import type {
  AdminSeller,
  AdminProduct,
  AdminOrder,
  AdminCustomer,
  AdminNotification,
  ChartPoint,
  CategoryPoint,
} from "./types";

// ─── Sellers ─────────────────────────────────────────────────────────────────

export const MOCK_SELLERS: AdminSeller[] = [
  {
    id: "s1",
    companyName: "Gulf Med Supplies",
    sellerName: "Khalid Al Rashidi",
    email: "khalid@gulfmed.ae",
    phone: "+971 50 234 5678",
    logoInitials: "GM",
    logoColor: "bg-blue-600",
    registrationDate: "2024-03-15",
    verificationStatus: "verified",
    productCount: 48,
    activeProducts: 42,
    totalSales: 1284,
    totalRevenueFils: 28940000,
    averageRating: 4.7,
    reviewCount: 342,
    commissionFils: 2894000,
    businessCategory: "Medicines",
    businessAddress: "Unit 14B, Healthcare City, Dubai, UAE",
    vatNumber: "AE100234567",
    lastActive: "2026-07-29",
    returnRate: 2.1,
    highestSellingProduct: "Nourisil MD Scar Gel",
    highestRatedProduct: "Calmi Relax Tablets",
    lowestRatedProduct: "Generic Paracetamol 500mg",
    bestCategory: "OTC Medicines",
    monthlyRevenue: [
      { label: "Aug", value: 195000 },
      { label: "Sep", value: 214000 },
      { label: "Oct", value: 228000 },
      { label: "Nov", value: 251000 },
      { label: "Dec", value: 318000 },
      { label: "Jan", value: 292000 },
      { label: "Feb", value: 308000 },
      { label: "Mar", value: 341000 },
      { label: "Apr", value: 363000 },
      { label: "May", value: 388000 },
      { label: "Jun", value: 409000 },
      { label: "Jul", value: 431000 },
    ],
    monthlySales: [
      { label: "Aug", value: 82 },
      { label: "Sep", value: 94 },
      { label: "Oct", value: 103 },
      { label: "Nov", value: 118 },
      { label: "Dec", value: 156 },
      { label: "Jan", value: 141 },
      { label: "Feb", value: 148 },
      { label: "Mar", value: 162 },
      { label: "Apr", value: 174 },
      { label: "May", value: 188 },
      { label: "Jun", value: 196 },
      { label: "Jul", value: 207 },
    ],
    categoryDistribution: [
      { label: "OTC Medicines", value: 55, color: "#6366f1" },
      { label: "Supplements", value: 25, color: "#22c55e" },
      { label: "Medical Devices", value: 20, color: "#f59e0b" },
    ],
  },
  {
    id: "s2",
    companyName: "HomeHaven Cosmetics",
    sellerName: "Aisha Al Mansoori",
    email: "aisha@homehaven.ae",
    phone: "+971 55 890 1234",
    logoInitials: "HH",
    logoColor: "bg-pink-500",
    registrationDate: "2024-05-22",
    verificationStatus: "verified",
    productCount: 34,
    activeProducts: 28,
    totalSales: 876,
    totalRevenueFils: 15430000,
    averageRating: 4.9,
    reviewCount: 218,
    commissionFils: 1543000,
    businessCategory: "Cosmetics",
    businessAddress: "Shop 3, Gold Souk Extension, Deira, Dubai, UAE",
    vatNumber: "AE100567890",
    lastActive: "2026-07-30",
    returnRate: 1.4,
    highestSellingProduct: "Bloom Skincare Starter Set",
    highestRatedProduct: "Rose Gold Lip Elixir",
    lowestRatedProduct: "Argan Shine Hair Oil",
    bestCategory: "Skincare",
    monthlyRevenue: [
      { label: "Aug", value: 98000 },
      { label: "Sep", value: 112000 },
      { label: "Oct", value: 121000 },
      { label: "Nov", value: 138000 },
      { label: "Dec", value: 175000 },
      { label: "Jan", value: 158000 },
      { label: "Feb", value: 167000 },
      { label: "Mar", value: 183000 },
      { label: "Apr", value: 196000 },
      { label: "May", value: 211000 },
      { label: "Jun", value: 224000 },
      { label: "Jul", value: 239000 },
    ],
    monthlySales: [
      { label: "Aug", value: 48 },
      { label: "Sep", value: 57 },
      { label: "Oct", value: 63 },
      { label: "Nov", value: 74 },
      { label: "Dec", value: 102 },
      { label: "Jan", value: 91 },
      { label: "Feb", value: 97 },
      { label: "Mar", value: 108 },
      { label: "Apr", value: 116 },
      { label: "May", value: 124 },
      { label: "Jun", value: 131 },
      { label: "Jul", value: 138 },
    ],
    categoryDistribution: [
      { label: "Skincare", value: 45, color: "#ec4899" },
      { label: "Lip Care", value: 30, color: "#f97316" },
      { label: "Hair Care", value: 25, color: "#8b5cf6" },
    ],
  },
  {
    id: "s3",
    companyName: "WellCare Direct",
    sellerName: "Mohammed Al Hashimi",
    email: "mohammed@wellcare.ae",
    phone: "+971 52 345 6789",
    logoInitials: "WD",
    logoColor: "bg-emerald-600",
    registrationDate: "2024-02-08",
    verificationStatus: "verified",
    productCount: 22,
    activeProducts: 20,
    totalSales: 542,
    totalRevenueFils: 8920000,
    averageRating: 4.4,
    reviewCount: 89,
    commissionFils: 892000,
    businessCategory: "Consumables",
    businessAddress: "Warehouse 7, Al Quoz Industrial Area 4, Dubai, UAE",
    vatNumber: "AE100789012",
    lastActive: "2026-07-28",
    returnRate: 3.2,
    highestSellingProduct: "WellCare First Aid Kit",
    highestRatedProduct: "Digital Thermometer Pro",
    lowestRatedProduct: "Disposable Gloves (100pk)",
    bestCategory: "First Aid",
    monthlyRevenue: [
      { label: "Aug", value: 54000 },
      { label: "Sep", value: 61000 },
      { label: "Oct", value: 67000 },
      { label: "Nov", value: 74000 },
      { label: "Dec", value: 89000 },
      { label: "Jan", value: 82000 },
      { label: "Feb", value: 87000 },
      { label: "Mar", value: 94000 },
      { label: "Apr", value: 101000 },
      { label: "May", value: 108000 },
      { label: "Jun", value: 114000 },
      { label: "Jul", value: 121000 },
    ],
    monthlySales: [
      { label: "Aug", value: 31 },
      { label: "Sep", value: 36 },
      { label: "Oct", value: 40 },
      { label: "Nov", value: 47 },
      { label: "Dec", value: 62 },
      { label: "Jan", value: 56 },
      { label: "Feb", value: 60 },
      { label: "Mar", value: 66 },
      { label: "Apr", value: 71 },
      { label: "May", value: 77 },
      { label: "Jun", value: 82 },
      { label: "Jul", value: 87 },
    ],
    categoryDistribution: [
      { label: "First Aid", value: 40, color: "#22c55e" },
      { label: "Diagnostics", value: 35, color: "#0ea5e9" },
      { label: "Personal Care", value: 25, color: "#f59e0b" },
    ],
  },
  {
    id: "s4",
    companyName: "Desert Rose Beauty",
    sellerName: "Fatima Al Zaabi",
    email: "fatima@desertrose.ae",
    phone: "+971 56 789 0123",
    logoInitials: "DR",
    logoColor: "bg-rose-500",
    registrationDate: "2026-07-10",
    verificationStatus: "pending",
    productCount: 0,
    activeProducts: 0,
    totalSales: 0,
    totalRevenueFils: 0,
    averageRating: 0,
    reviewCount: 0,
    commissionFils: 0,
    businessCategory: "Cosmetics",
    businessAddress: "Villa 22, Jumeirah 1, Dubai, UAE",
    vatNumber: "AE100345678",
    lastActive: "2026-07-10",
    returnRate: 0,
    highestSellingProduct: "—",
    highestRatedProduct: "—",
    lowestRatedProduct: "—",
    bestCategory: "—",
    monthlyRevenue: [],
    monthlySales: [],
    categoryDistribution: [],
  },
  {
    id: "s5",
    companyName: "Dubai Pharma Plus",
    sellerName: "Omar Al Farsi",
    email: "omar@dubaiph.ae",
    phone: "+971 50 123 4567",
    logoInitials: "DP",
    logoColor: "bg-indigo-600",
    registrationDate: "2026-07-18",
    verificationStatus: "pending",
    productCount: 0,
    activeProducts: 0,
    totalSales: 0,
    totalRevenueFils: 0,
    averageRating: 0,
    reviewCount: 0,
    commissionFils: 0,
    businessCategory: "Medicines",
    businessAddress: "Office 501, Business Bay Tower, Dubai, UAE",
    vatNumber: "AE100456789",
    lastActive: "2026-07-18",
    returnRate: 0,
    highestSellingProduct: "—",
    highestRatedProduct: "—",
    lowestRatedProduct: "—",
    bestCategory: "—",
    monthlyRevenue: [],
    monthlySales: [],
    categoryDistribution: [],
  },
  {
    id: "s6",
    companyName: "Emirates Health Store",
    sellerName: "Saeed Al Nuaimi",
    email: "saeed@emhealth.ae",
    phone: "+971 54 567 8901",
    logoInitials: "EH",
    logoColor: "bg-teal-600",
    registrationDate: "2024-08-12",
    verificationStatus: "verified",
    productCount: 31,
    activeProducts: 27,
    totalSales: 423,
    totalRevenueFils: 7680000,
    averageRating: 4.3,
    reviewCount: 67,
    commissionFils: 768000,
    businessCategory: "Medicines",
    businessAddress: "Ground Floor, Mirdif City Centre, Dubai, UAE",
    vatNumber: "AE100678901",
    lastActive: "2026-07-27",
    returnRate: 4.1,
    highestSellingProduct: "Omega-3 Fish Oil Capsules",
    highestRatedProduct: "Vitamin D3 2000IU",
    lowestRatedProduct: "Elderberry Immune Gummies",
    bestCategory: "Supplements",
    monthlyRevenue: [
      { label: "Aug", value: 42000 },
      { label: "Sep", value: 48000 },
      { label: "Oct", value: 53000 },
      { label: "Nov", value: 61000 },
      { label: "Dec", value: 79000 },
      { label: "Jan", value: 71000 },
      { label: "Feb", value: 76000 },
      { label: "Mar", value: 83000 },
      { label: "Apr", value: 89000 },
      { label: "May", value: 96000 },
      { label: "Jun", value: 102000 },
      { label: "Jul", value: 109000 },
    ],
    monthlySales: [
      { label: "Aug", value: 22 },
      { label: "Sep", value: 26 },
      { label: "Oct", value: 30 },
      { label: "Nov", value: 35 },
      { label: "Dec", value: 52 },
      { label: "Jan", value: 46 },
      { label: "Feb", value: 49 },
      { label: "Mar", value: 54 },
      { label: "Apr", value: 59 },
      { label: "May", value: 64 },
      { label: "Jun", value: 68 },
      { label: "Jul", value: 73 },
    ],
    categoryDistribution: [
      { label: "Supplements", value: 60, color: "#14b8a6" },
      { label: "OTC Medicines", value: 30, color: "#6366f1" },
      { label: "Wellness", value: 10, color: "#f59e0b" },
    ],
  },
  {
    id: "s7",
    companyName: "Al Noor Wellness",
    sellerName: "Layla Al Shamsi",
    email: "layla@alnoor.ae",
    phone: "+971 55 678 9012",
    logoInitials: "AN",
    logoColor: "bg-violet-500",
    registrationDate: "2024-11-30",
    verificationStatus: "verified",
    productCount: 19,
    activeProducts: 15,
    totalSales: 198,
    totalRevenueFils: 4230000,
    averageRating: 4.6,
    reviewCount: 44,
    commissionFils: 423000,
    businessCategory: "Cosmetics",
    businessAddress: "Shop 12, Mall of Emirates, Dubai, UAE",
    vatNumber: "AE100789123",
    lastActive: "2026-07-25",
    returnRate: 1.9,
    highestSellingProduct: "Mist Hydrating Facial Toner",
    highestRatedProduct: "Night Repair Serum",
    lowestRatedProduct: "Cleansing Milk",
    bestCategory: "Skincare",
    monthlyRevenue: [
      { label: "Aug", value: 21000 },
      { label: "Sep", value: 24000 },
      { label: "Oct", value: 27000 },
      { label: "Nov", value: 31000 },
      { label: "Dec", value: 43000 },
      { label: "Jan", value: 38000 },
      { label: "Feb", value: 41000 },
      { label: "Mar", value: 46000 },
      { label: "Apr", value: 51000 },
      { label: "May", value: 56000 },
      { label: "Jun", value: 61000 },
      { label: "Jul", value: 67000 },
    ],
    monthlySales: [
      { label: "Aug", value: 8 },
      { label: "Sep", value: 10 },
      { label: "Oct", value: 12 },
      { label: "Nov", value: 15 },
      { label: "Dec", value: 22 },
      { label: "Jan", value: 19 },
      { label: "Feb", value: 21 },
      { label: "Mar", value: 24 },
      { label: "Apr", value: 27 },
      { label: "May", value: 30 },
      { label: "Jun", value: 33 },
      { label: "Jul", value: 36 },
    ],
    categoryDistribution: [
      { label: "Skincare", value: 70, color: "#8b5cf6" },
      { label: "Makeup", value: 20, color: "#ec4899" },
      { label: "Wellness", value: 10, color: "#22c55e" },
    ],
  },
  {
    id: "s8",
    companyName: "MediCo Supplies",
    sellerName: "Tariq Al Rashid",
    email: "tariq@medico.ae",
    phone: "+971 50 890 1234",
    logoInitials: "MS",
    logoColor: "bg-slate-600",
    registrationDate: "2024-01-20",
    verificationStatus: "suspended",
    productCount: 15,
    activeProducts: 0,
    totalSales: 89,
    totalRevenueFils: 1240000,
    averageRating: 2.8,
    reviewCount: 23,
    commissionFils: 124000,
    businessCategory: "Medicines",
    businessAddress: "Office 101, Al Barsha 1, Dubai, UAE",
    vatNumber: "AE100123456",
    lastActive: "2026-06-15",
    returnRate: 12.4,
    highestSellingProduct: "Antiseptic Wipes",
    highestRatedProduct: "Antiseptic Wipes",
    lowestRatedProduct: "Cold & Flu Capsules",
    bestCategory: "Wound Care",
    monthlyRevenue: [
      { label: "Aug", value: 8000 },
      { label: "Sep", value: 9000 },
      { label: "Oct", value: 11000 },
      { label: "Nov", value: 12000 },
      { label: "Dec", value: 14000 },
      { label: "Jan", value: 13000 },
      { label: "Feb", value: 11000 },
      { label: "Mar", value: 9000 },
      { label: "Apr", value: 7000 },
      { label: "May", value: 6000 },
      { label: "Jun", value: 0 },
      { label: "Jul", value: 0 },
    ],
    monthlySales: [
      { label: "Aug", value: 6 },
      { label: "Sep", value: 7 },
      { label: "Oct", value: 9 },
      { label: "Nov", value: 11 },
      { label: "Dec", value: 14 },
      { label: "Jan", value: 12 },
      { label: "Feb", value: 10 },
      { label: "Mar", value: 8 },
      { label: "Apr", value: 6 },
      { label: "May", value: 4 },
      { label: "Jun", value: 0 },
      { label: "Jul", value: 0 },
    ],
    categoryDistribution: [
      { label: "OTC Medicines", value: 80, color: "#6366f1" },
      { label: "Wound Care", value: 20, color: "#22c55e" },
    ],
  },
  {
    id: "s9",
    companyName: "SkinGlow Arabia",
    sellerName: "Hessa Al Mazrouei",
    email: "hessa@skinglow.ae",
    phone: "+971 56 234 5678",
    logoInitials: "SG",
    logoColor: "bg-orange-500",
    registrationDate: "2026-06-02",
    verificationStatus: "rejected",
    productCount: 0,
    activeProducts: 0,
    totalSales: 0,
    totalRevenueFils: 0,
    averageRating: 0,
    reviewCount: 0,
    commissionFils: 0,
    businessCategory: "Cosmetics",
    businessAddress: "Flat 8, Jumeirah Lakes Towers, Dubai, UAE",
    vatNumber: "",
    lastActive: "2026-06-02",
    returnRate: 0,
    highestSellingProduct: "—",
    highestRatedProduct: "—",
    lowestRatedProduct: "—",
    bestCategory: "—",
    monthlyRevenue: [],
    monthlySales: [],
    categoryDistribution: [],
  },
  {
    id: "s10",
    companyName: "Bloom Beauty UAE",
    sellerName: "Noor Al Mansoori",
    email: "noor@bloomuae.ae",
    phone: "+971 52 456 7890",
    logoInitials: "BB",
    logoColor: "bg-fuchsia-500",
    registrationDate: "2026-07-25",
    verificationStatus: "pending",
    productCount: 0,
    activeProducts: 0,
    totalSales: 0,
    totalRevenueFils: 0,
    averageRating: 0,
    reviewCount: 0,
    commissionFils: 0,
    businessCategory: "Cosmetics",
    businessAddress: "Apartment 4B, Dubai Marina, Dubai, UAE",
    vatNumber: "AE100234891",
    lastActive: "2026-07-25",
    returnRate: 0,
    highestSellingProduct: "—",
    highestRatedProduct: "—",
    lowestRatedProduct: "—",
    bestCategory: "—",
    monthlyRevenue: [],
    monthlySales: [],
    categoryDistribution: [],
  },
];

// ─── Products ─────────────────────────────────────────────────────────────────

export const MOCK_PRODUCTS: AdminProduct[] = [
  {
    id: "p1",
    name: "PharmaGrow Biotin Hair Complex",
    slug: "pharmagrow-biotin",
    sellerId: "s1",
    sellerName: "Gulf Med Supplies",
    category: "Medicines",
    priceFils: 14500,
    approvalStatus: "pending_review",
    submittedDate: "2026-07-28",
    stock: 200,
    totalSold: 0,
    rating: 0,
    reviewCount: 0,
  },
  {
    id: "p2",
    name: "AquaGlow Premium Moisturiser",
    slug: "aquaglow-moisturiser",
    sellerId: "s2",
    sellerName: "HomeHaven Cosmetics",
    category: "Cosmetics",
    priceFils: 18900,
    approvalStatus: "pending_review",
    submittedDate: "2026-07-27",
    stock: 150,
    totalSold: 0,
    rating: 0,
    reviewCount: 0,
  },
  {
    id: "p3",
    name: "CoolBreeze Ultrasonic Humidifier",
    slug: "coolbreeze-humidifier",
    sellerId: "s3",
    sellerName: "WellCare Direct",
    category: "Consumables",
    priceFils: 32000,
    approvalStatus: "pending_review",
    submittedDate: "2026-07-26",
    stock: 45,
    totalSold: 0,
    rating: 0,
    reviewCount: 0,
  },
  {
    id: "p4",
    name: "ZenCalm Herbal Stress Relief Drops",
    slug: "zencalm-drops",
    sellerId: "s6",
    sellerName: "Emirates Health Store",
    category: "Medicines",
    priceFils: 9900,
    approvalStatus: "pending_review",
    submittedDate: "2026-07-25",
    stock: 300,
    totalSold: 0,
    rating: 0,
    reviewCount: 0,
  },
  {
    id: "p5",
    name: "Nourisil MD Scar Gel",
    slug: "nourisil-md",
    sellerId: "s1",
    sellerName: "Gulf Med Supplies",
    category: "Medicines",
    priceFils: 14900,
    approvalStatus: "approved",
    submittedDate: "2024-04-01",
    reviewedDate: "2024-04-03",
    stock: 89,
    totalSold: 412,
    rating: 5.0,
    reviewCount: 1,
  },
  {
    id: "p6",
    name: "Bloom Skincare Starter Set",
    slug: "bloom-skincare-set",
    sellerId: "s2",
    sellerName: "HomeHaven Cosmetics",
    category: "Cosmetics",
    priceFils: 22000,
    approvalStatus: "approved",
    submittedDate: "2024-06-10",
    reviewedDate: "2024-06-12",
    stock: 56,
    totalSold: 287,
    rating: 5.0,
    reviewCount: 1,
  },
  {
    id: "p7",
    name: "Calmi Relax Tablets",
    slug: "calmi-relax",
    sellerId: "s1",
    sellerName: "Gulf Med Supplies",
    category: "Medicines",
    priceFils: 8900,
    approvalStatus: "approved",
    submittedDate: "2024-04-05",
    reviewedDate: "2024-04-06",
    stock: 143,
    totalSold: 267,
    rating: 4.0,
    reviewCount: 1,
  },
  {
    id: "p8",
    name: "WellCare First Aid Kit Essentials",
    slug: "wellcare-first-aid-kit",
    sellerId: "s3",
    sellerName: "WellCare Direct",
    category: "Consumables",
    priceFils: 9200,
    approvalStatus: "approved",
    submittedDate: "2024-02-20",
    reviewedDate: "2024-02-22",
    stock: 112,
    totalSold: 198,
    rating: 4.5,
    reviewCount: 3,
  },
  {
    id: "p9",
    name: "Unlicensed Pain Relief Spray",
    slug: "unlicensed-spray",
    sellerId: "s8",
    sellerName: "MediCo Supplies",
    category: "Medicines",
    priceFils: 7500,
    approvalStatus: "rejected",
    submittedDate: "2026-05-10",
    reviewedDate: "2026-05-12",
    stock: 0,
    totalSold: 0,
    rating: 0,
    reviewCount: 0,
    rejectionReason: "Product lacks UAE Ministry of Health approval certificate.",
  },
  {
    id: "p10",
    name: "Expired Collagen Tablets",
    slug: "expired-collagen",
    sellerId: "s8",
    sellerName: "MediCo Supplies",
    category: "Medicines",
    priceFils: 5500,
    approvalStatus: "rejected",
    submittedDate: "2026-04-15",
    reviewedDate: "2026-04-17",
    stock: 0,
    totalSold: 0,
    rating: 0,
    reviewCount: 0,
    rejectionReason: "Product batch expiry date is within 30 days — not permitted.",
  },
];

// ─── Orders ───────────────────────────────────────────────────────────────────

export const MOCK_ORDERS: AdminOrder[] = [
  {
    id: "ORD-0081",
    customerId: "c1",
    customerName: "Ahmed Al Marzouqi",
    sellerId: "s1",
    sellerName: "Gulf Med Supplies",
    products: ["Nourisil MD Scar Gel", "Calmi Relax"],
    totalFils: 23800,
    commissionFils: 2380,
    status: "delivered",
    orderDate: "2026-07-20",
    city: "Dubai",
  },
  {
    id: "ORD-0082",
    customerId: "c2",
    customerName: "Sara Al Hamdan",
    sellerId: "s2",
    sellerName: "HomeHaven Cosmetics",
    products: ["Bloom Skincare Starter Set"],
    totalFils: 22000,
    commissionFils: 2200,
    status: "shipped",
    orderDate: "2026-07-26",
    city: "Abu Dhabi",
  },
  {
    id: "ORD-0083",
    customerId: "c3",
    customerName: "Layla Karim",
    sellerId: "s3",
    sellerName: "WellCare Direct",
    products: ["WellCare First Aid Kit", "Digital Thermometer"],
    totalFils: 15100,
    commissionFils: 1510,
    status: "processing",
    orderDate: "2026-07-28",
    city: "Sharjah",
  },
  {
    id: "ORD-0084",
    customerId: "c4",
    customerName: "Fatima Al Balushi",
    sellerId: "s2",
    sellerName: "HomeHaven Cosmetics",
    products: ["Rose Gold Lip Elixir", "Mist Facial Toner"],
    totalFils: 14100,
    commissionFils: 1410,
    status: "delivered",
    orderDate: "2026-07-15",
    city: "Dubai",
  },
  {
    id: "ORD-0085",
    customerId: "c5",
    customerName: "Mohammed Al Khoori",
    sellerId: "s6",
    sellerName: "Emirates Health Store",
    products: ["Omega-3 Fish Oil"],
    totalFils: 8900,
    commissionFils: 890,
    status: "returned",
    orderDate: "2026-07-10",
    city: "Ajman",
  },
  {
    id: "ORD-0086",
    customerId: "c1",
    customerName: "Ahmed Al Marzouqi",
    sellerId: "s1",
    sellerName: "Gulf Med Supplies",
    products: ["Vitamin D3 5000IU"],
    totalFils: 11200,
    commissionFils: 1120,
    status: "delivered",
    orderDate: "2026-07-18",
    city: "Dubai",
  },
  {
    id: "ORD-0087",
    customerId: "c6",
    customerName: "Nadia Al Rashidi",
    sellerId: "s2",
    sellerName: "HomeHaven Cosmetics",
    products: ["Glow Vitamin C Serum"],
    totalFils: 15500,
    commissionFils: 1550,
    status: "shipped",
    orderDate: "2026-07-27",
    city: "Ras Al Khaimah",
  },
  {
    id: "ORD-0088",
    customerId: "c7",
    customerName: "Khalil Al Zaabi",
    sellerId: "s3",
    sellerName: "WellCare Direct",
    products: ["Blood Pressure Monitor"],
    totalFils: 21500,
    commissionFils: 2150,
    status: "cancelled",
    orderDate: "2026-07-22",
    city: "Dubai",
  },
  {
    id: "ORD-0089",
    customerId: "c8",
    customerName: "Mariam Al Hosani",
    sellerId: "s7",
    sellerName: "Al Noor Wellness",
    products: ["Mist Hydrating Facial Toner", "Night Repair Serum"],
    totalFils: 18900,
    commissionFils: 1890,
    status: "delivered",
    orderDate: "2026-07-24",
    city: "Dubai",
  },
  {
    id: "ORD-0090",
    customerId: "c2",
    customerName: "Sara Al Hamdan",
    sellerId: "s6",
    sellerName: "Emirates Health Store",
    products: ["Vitamin D3 2000IU", "Elderberry Gummies"],
    totalFils: 12400,
    commissionFils: 1240,
    status: "pending",
    orderDate: "2026-07-30",
    city: "Abu Dhabi",
  },
];

// ─── Customers ────────────────────────────────────────────────────────────────

export const MOCK_CUSTOMERS: AdminCustomer[] = [
  {
    id: "c1",
    name: "Ahmed Al Marzouqi",
    email: "ahmed@email.com",
    phone: "+971 50 111 2233",
    registrationDate: "2024-04-10",
    totalOrders: 14,
    totalSpentFils: 184500,
    lastActive: "2026-07-28",
    city: "Dubai",
  },
  {
    id: "c2",
    name: "Sara Al Hamdan",
    email: "sara@email.com",
    phone: "+971 55 334 4556",
    registrationDate: "2024-07-15",
    totalOrders: 8,
    totalSpentFils: 98200,
    lastActive: "2026-07-26",
    city: "Abu Dhabi",
  },
  {
    id: "c3",
    name: "Layla Karim",
    email: "layla@email.com",
    phone: "+971 52 667 7889",
    registrationDate: "2025-01-22",
    totalOrders: 5,
    totalSpentFils: 47800,
    lastActive: "2026-07-28",
    city: "Sharjah",
  },
  {
    id: "c4",
    name: "Fatima Al Balushi",
    email: "fatima.b@email.com",
    phone: "+971 56 889 9001",
    registrationDate: "2025-03-08",
    totalOrders: 11,
    totalSpentFils: 132400,
    lastActive: "2026-07-25",
    city: "Dubai",
  },
  {
    id: "c5",
    name: "Mohammed Al Khoori",
    email: "mohd@email.com",
    phone: "+971 54 112 2334",
    registrationDate: "2024-09-14",
    totalOrders: 3,
    totalSpentFils: 28900,
    lastActive: "2026-07-15",
    city: "Ajman",
  },
  {
    id: "c6",
    name: "Nadia Al Rashidi",
    email: "nadia@email.com",
    phone: "+971 50 445 5667",
    registrationDate: "2025-06-30",
    totalOrders: 7,
    totalSpentFils: 86700,
    lastActive: "2026-07-27",
    city: "Ras Al Khaimah",
  },
  {
    id: "c7",
    name: "Khalil Al Zaabi",
    email: "khalil@email.com",
    phone: "+971 55 778 8990",
    registrationDate: "2026-01-15",
    totalOrders: 2,
    totalSpentFils: 21500,
    lastActive: "2026-07-22",
    city: "Dubai",
  },
  {
    id: "c8",
    name: "Mariam Al Hosani",
    email: "mariam@email.com",
    phone: "+971 52 001 1223",
    registrationDate: "2024-12-20",
    totalOrders: 9,
    totalSpentFils: 114300,
    lastActive: "2026-07-29",
    city: "Dubai",
  },
  {
    id: "c9",
    name: "Yousef Al Hamad",
    email: "yousef@email.com",
    phone: "+971 54 334 5566",
    registrationDate: "2026-05-11",
    totalOrders: 1,
    totalSpentFils: 9900,
    lastActive: "2026-06-20",
    city: "Fujairah",
  },
  {
    id: "c10",
    name: "Reem Al Suwaidi",
    email: "reem@email.com",
    phone: "+971 56 556 7788",
    registrationDate: "2025-09-05",
    totalOrders: 6,
    totalSpentFils: 72300,
    lastActive: "2026-07-29",
    city: "Dubai",
  },
];

// ─── Notifications ────────────────────────────────────────────────────────────

export const MOCK_NOTIFICATIONS: AdminNotification[] = [
  {
    id: "n1",
    type: "seller_registration",
    title: "New Seller Registration",
    message: "Bloom Beauty UAE has submitted a seller registration and is awaiting review.",
    timestamp: "2026-07-25T09:14:00Z",
    read: false,
    entityId: "s10",
    entityType: "seller",
    severity: "info",
  },
  {
    id: "n2",
    type: "seller_verification",
    title: "Seller Awaiting Verification",
    message: "Dubai Pharma Plus has been pending verification for 12 days. Action required.",
    timestamp: "2026-07-18T14:22:00Z",
    read: false,
    entityId: "s5",
    entityType: "seller",
    severity: "warning",
  },
  {
    id: "n3",
    type: "product_approval",
    title: "Products Pending Approval",
    message: "4 products submitted by verified sellers are pending your review.",
    timestamp: "2026-07-28T10:30:00Z",
    read: false,
    severity: "info",
  },
  {
    id: "n4",
    type: "high_return",
    title: "High Return Rate Alert",
    message: "MediCo Supplies has a 12.4% return rate — above the 5% threshold. Review recommended.",
    timestamp: "2026-07-20T08:45:00Z",
    read: false,
    entityId: "s8",
    entityType: "seller",
    severity: "error",
  },
  {
    id: "n5",
    type: "large_order",
    title: "Large Order Placed",
    message: "Ahmed Al Marzouqi placed a bulk order totalling AED 238.00 from Gulf Med Supplies.",
    timestamp: "2026-07-20T15:11:00Z",
    read: true,
    entityId: "ORD-0081",
    entityType: "order",
    severity: "success",
  },
  {
    id: "n6",
    type: "seller_registration",
    title: "New Seller Registration",
    message: "Desert Rose Beauty has submitted a seller registration request.",
    timestamp: "2026-07-10T11:08:00Z",
    read: true,
    entityId: "s4",
    entityType: "seller",
    severity: "info",
  },
  {
    id: "n7",
    type: "low_stock",
    title: "Low Stock Warning",
    message: "WellCare Direct's 'CoolBreeze Humidifier' has only 12 units remaining.",
    timestamp: "2026-07-24T16:30:00Z",
    read: true,
    entityId: "p3",
    entityType: "product",
    severity: "warning",
  },
  {
    id: "n8",
    type: "product_rejected",
    title: "Product Rejected",
    message: "MediCo Supplies' 'Unlicensed Pain Relief Spray' was rejected — missing MOH certificate.",
    timestamp: "2026-05-12T09:00:00Z",
    read: true,
    entityId: "p9",
    entityType: "product",
    severity: "error",
  },
];

// ─── Platform-wide analytics ──────────────────────────────────────────────────

export const PLATFORM_MONTHLY_REVENUE: ChartPoint[] = [
  { label: "Aug", value: 185000 },
  { label: "Sep", value: 214000 },
  { label: "Oct", value: 238000 },
  { label: "Nov", value: 267000 },
  { label: "Dec", value: 342000 },
  { label: "Jan", value: 309000 },
  { label: "Feb", value: 328000 },
  { label: "Mar", value: 361000 },
  { label: "Apr", value: 389000 },
  { label: "May", value: 418000 },
  { label: "Jun", value: 441000 },
  { label: "Jul", value: 468000 },
];

export const PLATFORM_MONTHLY_ORDERS: ChartPoint[] = [
  { label: "Aug", value: 42 },
  { label: "Sep", value: 58 },
  { label: "Oct", value: 67 },
  { label: "Nov", value: 84 },
  { label: "Dec", value: 124 },
  { label: "Jan", value: 108 },
  { label: "Feb", value: 116 },
  { label: "Mar", value: 134 },
  { label: "Apr", value: 148 },
  { label: "May", value: 163 },
  { label: "Jun", value: 172 },
  { label: "Jul", value: 181 },
];

export const PLATFORM_CUSTOMER_GROWTH: ChartPoint[] = [
  { label: "Aug", value: 120 },
  { label: "Sep", value: 198 },
  { label: "Oct", value: 312 },
  { label: "Nov", value: 487 },
  { label: "Dec", value: 634 },
  { label: "Jan", value: 743 },
  { label: "Feb", value: 834 },
  { label: "Mar", value: 932 },
  { label: "Apr", value: 1041 },
  { label: "May", value: 1148 },
  { label: "Jun", value: 1221 },
  { label: "Jul", value: 1284 },
];

export const PLATFORM_SELLER_GROWTH: ChartPoint[] = [
  { label: "Aug", value: 3 },
  { label: "Sep", value: 5 },
  { label: "Oct", value: 6 },
  { label: "Nov", value: 8 },
  { label: "Dec", value: 9 },
  { label: "Jan", value: 9 },
  { label: "Feb", value: 9 },
  { label: "Mar", value: 10 },
  { label: "Apr", value: 10 },
  { label: "May", value: 10 },
  { label: "Jun", value: 10 },
  { label: "Jul", value: 10 },
];

export const PLATFORM_COMMISSION: ChartPoint[] = PLATFORM_MONTHLY_REVENUE.map((p) => ({
  label: p.label,
  value: Math.round(p.value * 0.1),
}));

export const CATEGORY_DISTRIBUTION: CategoryPoint[] = [
  { label: "Medicines", value: 45, color: "#6366f1" },
  { label: "Cosmetics", value: 35, color: "#ec4899" },
  { label: "Consumables", value: 20, color: "#22c55e" },
];
